version: '3'
services:
  nodeconfig:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nodeconfig
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=nodeconfig
      - DB_PASSWORD=nodeconfig123
      - DB_NAME=nodeconfig_db
      - SESSION_SECRET=your-session-secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./src:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      nodeconfig_net:
        ipv4_address: 172.21.0.2
    dns:
      - 8.8.8.8
      - 114.114.114.114
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    mem_limit: 1G
    memswap_limit: 2G

  mysql:
    image: mysql:8.0
    container_name: nodeconfig-mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb_buffer_pool_size=128M
      --innodb_log_buffer_size=16M
      --max_connections=100
      --skip-name-resolve
      --skip-host-cache
      --innodb_flush_log_at_trx_commit=2
      --sync_binlog=0
      --innodb_flush_method=O_DIRECT
      --performance_schema=OFF
      --table_open_cache=400
      --table_definition_cache=400
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=nodeconfig_db
      - MYSQL_USER=nodeconfig
      - MYSQL_PASSWORD=nodeconfig123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      nodeconfig_net:
        ipv4_address: 172.21.0.3
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 512M
    memswap_limit: 1G

  redis:
    image: redis:alpine
    container_name: nodeconfig-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      nodeconfig_net:
        ipv4_address: 172.21.0.5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nodeconfig-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root123
      - PMA_USER=nodeconfig
      - PMA_PASSWORD=nodeconfig123
      - UPLOAD_LIMIT=300M
      - PMA_ABSOLUTE_URI=http://${SERVER_IP:-localhost}:8080/
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      nodeconfig_net:
        ipv4_address: 172.21.0.4

volumes:
  mysql_data:
  node_modules:
  redis_data:

networks:
  nodeconfig_net:
    external: true
