version: "3"
services:
  nodeconfig:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodeconfig
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=nodeconfig
      - DB_PASSWORD=nodeconfig123
      - DB_NAME=nodeconfig_db
      - SERVER_IP=${SERVER_IP:-localhost}
    volumes:
      - ./src:/app/src
      - node_modules:/app/src/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      nodeconfig_net:
        ipv4_address: 172.20.0.2

  mysql:
    image: mysql:8.0
    container_name: nodeconfig-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=nodeconfig_db
      - MYSQL_USER=nodeconfig
      - MYSQL_PASSWORD=nodeconfig123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "nodeconfig", "-pnodeconfig123"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      nodeconfig_net:
        ipv4_address: 172.20.0.3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nodeconfig-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root123
      - PMA_USER=nodeconfig
      - PMA_PASSWORD=nodeconfig123
      - UPLOAD_LIMIT=300M
      - PMA_ABSOLUTE_URI=http://${SERVER_IP:-localhost}:8080/
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      nodeconfig_net:
        ipv4_address: 172.20.0.4

volumes:
  mysql_data:
  node_modules:

networks:
  nodeconfig_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
